name: tacticum_converter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.17
  either_dart: ^1.0.0
  http: ^1.3.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true